merge:
 doc: "__template__"     # required
 chapter: "loremipsum1"  # default: ""

convert:
 input: "__out__/__template___loremipsum1.md"
 format: "html"
 output: "__out__/__template__loremipsum1.html"
 multi_output: "__out__"